name: Readme Update Blog
on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch: # run on workflow dispatch

jobs:
  update-blog:
    name: Update latest blogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch medium.com posts
        uses: imskr/readme-update-actions@main
        with:
          rss_list: "https://imskr.medium.com/feed"
