name: Latest blogs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-blog:
    name: Update latest blogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch from medium.com
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://imskr.medium.com/feed"
          max_post_count: 3
