name: Open Source Contributions
on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch: # run on workflow dispatch

jobs:
  update-contributions:
    name: Update latest contributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Contributions Badge
        uses: imskr/contributions-badge@v0.2
        with:
          organization: "gitlab-org"
          project: "gitlab"
          username: "imskr"
